### PR TITLE
cu 4/8

### PR DESCRIPTION
**Pull request by tkcy**

### CODE REVIEW

**Comment by kjsato** [comment]
@tkcy Could you check the file out whether it was the last week's?

**Comment by tkcy** [comment]
You're right, sorry about that - updated file attached.

**Comment by kjsato** [comment]
@tkcy Thank you for your update. And I had the file updated in origin_date col so please check it out.

**Comment by kjsato** [comment]
I proceed it because no problem is seen(sorry). The current output reflected your submission is:
https://hopkinsidd.github.io/rsv-forecast-hub_website/

**Comment by tkcy** [comment]
That's fine thank you! You don't need to check every week, it's fine to proceed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Koji SATO ***@***.***>
Sent: Tuesday, April 9, 2024 4:15:31 PM
To: HopkinsIDD/rsv-forecast-hub ***@***.***>
Cc: Yamana, Teresa K. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [HopkinsIDD/rsv-forecast-hub] cu 4/8 (PR #47)


I proceed it because no problem is seen(sorry). The current output reflected your submission is:
https://hopkinsidd.github.io/rsv-forecast-hub_website/

**Pull request merged**
