### PR TITLE
PSI-PROF weekly submission - 24 Mar 2024

### PR DESCRIPTION
**Pull request by jturtle**

### CODE REVIEW

**Comment by kjsato** [comment]
Thanks for your submissions. I'd like to notify that your model-output file (including the former submissions) data is 1w behind our expected origin_date, and the output is not reflected on website(2024-03-24 for this week). We would appreciate it if you could reflect that in the data one week ahead,

Thank you,

**Comment by jturtle** [comment]
Hi Koji,
Sorry, I did not originally see this message.  Thank you for reaching out.

In our most recent submission, we used all available data (through March
16) and thus set origin_date to March 17.  Is this incorrect?  Are you
saying that origin_date should be March 24?  If this is the case, is
horizon=0 the week containing March 17 or the week containing March 24?

Thank you in advance for the clarifications,
Jamie

**Comment by kjsato** [comment]
@jturtle sorry for my late response and the inconvienence. Yes, in this week's submission (2024-3-24), we would have expected to have data with origin_date 2024-03-24 of which filename would be 2024-03-24-PSI-PROF.parquet, and it contains the week from 03-24 with horizon=0 in your case.

In this case, at the time of data processing, filename was a date in the past (if origin_date was a date in the past, the file name would be the same of course), so it was excluded from processing.
At least filename and data cannot go back in time, so I would appreciate it if you could set filename (e.g, 2024-03-24-PSI-PROF.parquet) and the data to match this week's (with origin_date "2024-03-24").

Thank you,

**Comment by jturtle** [comment]
Thank you for the clarifications.  I have just submitted a pull request
that includes a properly dated forecast for this week.  Our pipeline has
been updated, so next week's forecast should be on-time and properly dated.
Best,
Jamie

**Pull request merged**
